language: d

matrix:
  include:
      - d: dmd-2.090.1
      - d: dmd-2.088.1
      - d: dmd-2.087.1
      - d: dmd-2.086.1
      - d: dmd-2.079.1
      - d: ldc-1.20.0
      - d: ldc-1.19.0
      - d: ldc-1.18.0
      - d: ldc-1.17.0
      - d: ldc-1.16.0
      - d: ldc-1.9.0

script:
  - dub test --compiler=${DC} gfm7:core
  - dub test --compiler=${DC} gfm7:sdl2
  - dub test --compiler=${DC} gfm7:opengl
  - dub test --compiler=${DC} gfm7:assimp
  - dub test --compiler=${DC} gfm7:freeimage
  - dub test --compiler=${DC} gfm7:logger
