dub test gfm7:core      -a x86    --compiler dmd
dub test gfm7:core      -a x86_64 --compiler dmd
dub test gfm7:core      -a x86    --compiler ldc2
dub test gfm7:core      -a x86_64 --compiler ldc2
dub test gfm7:net       -a x86    --compiler dmd
dub test gfm7:net       -a x86_64 --compiler dmd
dub test gfm7:net       -a x86    --compiler ldc2
dub test gfm7:net       -a x86_64 --compiler ldc2
dub test gfm7:enet      -a x86    --compiler dmd
dub test gfm7:enet      -a x86_64 --compiler dmd
dub test gfm7:enet      -a x86    --compiler ldc2
dub test gfm7:enet      -a x86_64 --compiler ldc2
dub test gfm7:sdl2      -a x86    --compiler dmd
dub test gfm7:sdl2      -a x86_64 --compiler dmd
dub test gfm7:sdl2      -a x86    --compiler ldc2
dub test gfm7:sdl2      -a x86_64 --compiler ldc2
dub test gfm7:opengl    -a x86    --compiler dmd
dub test gfm7:opengl    -a x86_64 --compiler dmd
dub test gfm7:opengl    -a x86    --compiler ldc2
dub test gfm7:opengl    -a x86_64 --compiler ldc2
dub test gfm7:assimp    -a x86    --compiler dmd
dub test gfm7:assimp    -a x86_64 --compiler dmd
dub test gfm7:assimp    -a x86    --compiler ldc2
dub test gfm7:assimp    -a x86_64 --compiler ldc2
dub test gfm7:freeimage -a x86    --compiler dmd
dub test gfm7:freeimage -a x86_64 --compiler dmd
dub test gfm7:freeimage -a x86    --compiler ldc2
dub test gfm7:freeimage -a x86_64 --compiler ldc2
dub test gfm7:image     -a x86    --compiler dmd
dub test gfm7:image     -a x86_64 --compiler dmd
dub test gfm7:image     -a x86    --compiler ldc2
dub test gfm7:image     -a x86_64 --compiler ldc2
dub test gfm7:logger    -a x86    --compiler dmd
dub test gfm7:logger    -a x86_64 --compiler dmd
dub test gfm7:logger    -a x86    --compiler ldc2
dub test gfm7:logger    -a x86_64 --compiler ldc2
