name: Testsuite

on:
  push:
    branches: [ master, github-actions ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        # Latest stable version, update at will
        os: [ macos-13, ubuntu-22.04, windows-2022 ]
        dc: [ dmd-latest, ldc-latest, dmd-master, ldc-master ]

    runs-on: ${{ matrix.os }}

    steps:
    # Compiler to test with
    - name: Prepare compiler
      uses: dlang-community/setup-dlang@v1
      with:
        compiler: ${{ matrix.dc }}

    # Checkout the repository
    - name: Checkout
      uses: actions/checkout@v4

    - name: 'Build & Test'
      run: |
        dub build --compiler=${{ env.DC }} gfm7:sdl2
        dub test  --compiler=${{ env.DC }} gfm7:sdl2
        dub build --compiler=${{ env.DC }} gfm7:opengl
        dub test  --compiler=${{ env.DC }} gfm7:opengl
